ScontrolBundle:
    resource: "@ScontrolBundle/Resources/config/routing.yml"
    prefix:   /scon

#Index Producción
Index_prod:
    pattern: /
    defaults: { _controller: ScontrolBundle:Mdhist:index }

# Seguridad
login:
    pattern: /login
    defaults: { _controller: ScontrolBundle:Guard:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
